/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Đặng Huy
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        QuanLySV = new javax.swing.JButton();
        tbnQLKTX = new javax.swing.JButton();
        tbnDanhGia = new javax.swing.JButton();
        QuanLyLT = new javax.swing.JButton();
        tbnThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Trang chủ hệ thống");

        QuanLySV.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        QuanLySV.setText("QUẢN LÝ SINH VIÊN");
        QuanLySV.setToolTipText("");
        QuanLySV.setActionCommand("JButton1");
        QuanLySV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLySVActionPerformed(evt);
            }
        });

        tbnQLKTX.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbnQLKTX.setText("QUẢN LÝ KÝ TÚC XÁ");
        tbnQLKTX.setToolTipText("");
        tbnQLKTX.setActionCommand("JButton1");
        tbnQLKTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnQLKTXActionPerformed(evt);
            }
        });

        tbnDanhGia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbnDanhGia.setText("ĐÁNH GIÁ RÈN LUYỆN");
        tbnDanhGia.setToolTipText("");
        tbnDanhGia.setActionCommand("JButton1");
        tbnDanhGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnDanhGiaActionPerformed(evt);
            }
        });

        QuanLyLT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        QuanLyLT.setText("LỊCH THI");
        QuanLyLT.setToolTipText("");
        QuanLyLT.setActionCommand("JButton1");
        QuanLyLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyLTActionPerformed(evt);
            }
        });

        tbnThongKe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbnThongKe.setText("THỐNG KÊ");
        tbnThongKe.setToolTipText("");
        tbnThongKe.setActionCommand("JButton1");
        tbnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QuanLySV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbnDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(237, 237, 237))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuanLyLT, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(tbnQLKTX, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuanLySV, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnQLKTX, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuanLyLT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbnDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuanLySVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLySVActionPerformed
        // TODO add your handling code here:
        QuanLySV QLSV = new QuanLySV();
        QLSV.setVisible(true);
        dispose();

    }//GEN-LAST:event_QuanLySVActionPerformed

    private void tbnQLKTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnQLKTXActionPerformed
        // TODO add your handling code here:
        QuanLyKTX KTX = new QuanLyKTX();
        KTX.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_tbnQLKTXActionPerformed

    private void tbnDanhGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnDanhGiaActionPerformed
        // TODO add your handling code here:
        DanhGia danhgia = new DanhGia();
        danhgia.setVisible(true);
        dispose(); 
    }//GEN-LAST:event_tbnDanhGiaActionPerformed

    private void QuanLyLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyLTActionPerformed
        // TODO add your handling code here:
        QuanLyLichThi QLLT = new QuanLyLichThi();
        QLLT.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuanLyLTActionPerformed

    private void tbnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnThongKeActionPerformed
        ThongKe thongke = new ThongKe();
        thongke.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_tbnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuanLyLT;
    private javax.swing.JButton QuanLySV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tbnDanhGia;
    private javax.swing.JButton tbnQLKTX;
    private javax.swing.JButton tbnThongKe;
    // End of variables declaration//GEN-END:variables
}
