/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CSDL.MonHoc;
import CSDL.SinhVien;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import static java.nio.file.Files.list;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.HashMap;
import java.util.Map;
import java.util.jar.Attributes.Name;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin Luu Viet Nghia
 */
public class ThongKe extends javax.swing.JFrame {

    private Object txtTke;
    private Object listD_A;

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMon = new javax.swing.JTextField();
        btnTKe = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tk00 = new javax.swing.JTextField();
        tk01 = new javax.swing.JTextField();
        tk02 = new javax.swing.JTextField();
        tk03 = new javax.swing.JTextField();
        tk04 = new javax.swing.JTextField();
        tk05 = new javax.swing.JTextField();
        tk06 = new javax.swing.JTextField();
        tk07 = new javax.swing.JTextField();
        tk08 = new javax.swing.JTextField();
        tk09 = new javax.swing.JTextField();
        tk10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tl00 = new javax.swing.JTextField();
        tl01 = new javax.swing.JTextField();
        tl02 = new javax.swing.JTextField();
        tl03 = new javax.swing.JTextField();
        tl04 = new javax.swing.JTextField();
        tl05 = new javax.swing.JTextField();
        tl06 = new javax.swing.JTextField();
        tl07 = new javax.swing.JTextField();
        tl08 = new javax.swing.JTextField();
        tl09 = new javax.swing.JTextField();
        tl10 = new javax.swing.JTextField();
        tl11 = new javax.swing.JTextField();
        tk11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnBack.setText("TRỜ VỀ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BẢNG THỐNG KÊ SINH VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tên môn");

        txtMon.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMonInputMethodTextChanged(evt);
            }
        });

        btnTKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTKe.setText("Thống kê");
        btnTKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKeActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(25, 25, 25));
        jLabel3.setText("Mức điểm");
        jLabel3.setAlignmentY(2.0F);
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setForeground(new java.awt.Color(25, 25, 25));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");
        jLabel4.setAlignmentY(2.0F);
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setForeground(new java.awt.Color(25, 25, 25));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1");
        jLabel5.setAlignmentY(2.0F);
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setForeground(new java.awt.Color(25, 25, 25));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2");
        jLabel6.setAlignmentY(2.0F);
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setForeground(new java.awt.Color(25, 25, 25));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3");
        jLabel7.setAlignmentY(2.0F);
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setForeground(new java.awt.Color(25, 25, 25));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("4");
        jLabel8.setAlignmentY(2.0F);
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setForeground(new java.awt.Color(25, 25, 25));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("5");
        jLabel9.setAlignmentY(2.0F);
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setForeground(new java.awt.Color(25, 25, 25));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("6");
        jLabel10.setAlignmentY(2.0F);
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel11.setForeground(new java.awt.Color(25, 25, 25));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("7");
        jLabel11.setAlignmentY(2.0F);
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setForeground(new java.awt.Color(25, 25, 25));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("8");
        jLabel12.setAlignmentY(2.0F);
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setForeground(new java.awt.Color(25, 25, 25));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("9");
        jLabel13.setAlignmentY(2.0F);
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setForeground(new java.awt.Color(25, 25, 25));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("10");
        jLabel14.setAlignmentY(2.0F);
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setForeground(new java.awt.Color(25, 25, 25));
        jLabel15.setText("Số lượng");
        jLabel15.setAlignmentY(2.0F);
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk00.setForeground(new java.awt.Color(25, 25, 25));
        tk00.setAlignmentY(2.0F);
        tk00.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk01.setForeground(new java.awt.Color(25, 25, 25));
        tk01.setAlignmentY(2.0F);
        tk01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk02.setForeground(new java.awt.Color(25, 25, 25));
        tk02.setAlignmentY(2.0F);
        tk02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk03.setForeground(new java.awt.Color(25, 25, 25));
        tk03.setAlignmentY(2.0F);
        tk03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk04.setForeground(new java.awt.Color(25, 25, 25));
        tk04.setAlignmentY(2.0F);
        tk04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk05.setForeground(new java.awt.Color(25, 25, 25));
        tk05.setAlignmentY(2.0F);
        tk05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk06.setForeground(new java.awt.Color(25, 25, 25));
        tk06.setAlignmentY(2.0F);
        tk06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk06.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk06ActionPerformed(evt);
            }
        });

        tk07.setForeground(new java.awt.Color(25, 25, 25));
        tk07.setAlignmentY(2.0F);
        tk07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk07.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk07ActionPerformed(evt);
            }
        });

        tk08.setForeground(new java.awt.Color(25, 25, 25));
        tk08.setAlignmentY(2.0F);
        tk08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk08.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk08ActionPerformed(evt);
            }
        });

        tk09.setForeground(new java.awt.Color(25, 25, 25));
        tk09.setAlignmentY(2.0F);
        tk09.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk09.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk09ActionPerformed(evt);
            }
        });

        tk10.setForeground(new java.awt.Color(25, 25, 25));
        tk10.setAlignmentY(2.0F);
        tk10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk10ActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(25, 25, 25));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tổng");
        jLabel16.setAlignmentY(2.0F);
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel17.setForeground(new java.awt.Color(25, 25, 25));
        jLabel17.setText("Tỷ lệ");
        jLabel17.setAlignmentY(2.0F);
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl00.setForeground(new java.awt.Color(25, 25, 25));
        tl00.setAlignmentY(2.0F);
        tl00.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl01.setForeground(new java.awt.Color(25, 25, 25));
        tl01.setAlignmentY(2.0F);
        tl01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl02.setForeground(new java.awt.Color(25, 25, 25));
        tl02.setAlignmentY(2.0F);
        tl02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl03.setForeground(new java.awt.Color(25, 25, 25));
        tl03.setAlignmentY(2.0F);
        tl03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tl03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tl03ActionPerformed(evt);
            }
        });

        tl04.setForeground(new java.awt.Color(25, 25, 25));
        tl04.setAlignmentY(2.0F);
        tl04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl05.setForeground(new java.awt.Color(25, 25, 25));
        tl05.setAlignmentY(2.0F);
        tl05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl06.setForeground(new java.awt.Color(25, 25, 25));
        tl06.setAlignmentY(2.0F);
        tl06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl06.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl07.setForeground(new java.awt.Color(25, 25, 25));
        tl07.setAlignmentY(2.0F);
        tl07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl07.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl08.setForeground(new java.awt.Color(25, 25, 25));
        tl08.setAlignmentY(2.0F);
        tl08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl08.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl09.setForeground(new java.awt.Color(25, 25, 25));
        tl09.setAlignmentY(2.0F);
        tl09.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl09.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl10.setForeground(new java.awt.Color(25, 25, 25));
        tl10.setAlignmentY(2.0F);
        tl10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl11.setForeground(new java.awt.Color(25, 25, 25));
        tl11.setAlignmentY(2.0F);
        tl11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tl11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tl11ActionPerformed(evt);
            }
        });

        tk11.setForeground(new java.awt.Color(25, 25, 25));
        tk11.setAlignmentY(2.0F);
        tk11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tk11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTKe, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(tk00, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tk02, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(tk01, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(tk03, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(tk04, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addComponent(tk05, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tk09, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tk08, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tk06, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tk10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tk11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tl01, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tl06, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(tl02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tl00, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(tl03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tl04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(tl05, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tl11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(tl10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tl09, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(tl08, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(3, 3, 3))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tk07, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tl07, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(91, 91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTKe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tk00)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tk01)
                    .addComponent(tl01)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tl03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tk03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tl02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tk04, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tl04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tk05, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl05, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tk06, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tk07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tk08, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl08))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tk09, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl09, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tk10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tk11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tl11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tk02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKeActionPerformed
        // TODO add your handling code here:
        int d0 = 0;
        double Tl0=0;
        int d1 = 0;
        double Tl1=0;
        int d2 = 0;
        double Tl2=0;
        int d3 = 0;
        double Tl3=0;
        int d4 = 0;
        double Tl4=0;
        int d5 = 0;
        double Tl5=0;
        int d6 = 0;
        double Tl6=0;
        int d7 = 0;
        double Tl7=0;
        int d8 = 0;
        double Tl8=0;
        int d9 = 0;
        double Tl9=0;
        int d10 = 0;
        double x=0;
        int d = 10;
        double Tl=0;

        String mon = txtMon.getText();
        if (mon.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui long nhap mon can thong ke!", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                ArrayList<MonHoc> listMH = MHFromFile();
                ArrayList<SinhVien> listSV = SVFromFile();
//                ArrayList<D_A> listD_A = DAFromFile();
                if (checkMon(mon, listMH)) {   
                    Map<String, Integer> diemIndexes = new HashMap<>();
                diemIndexes.put("DiemA", 6);
                diemIndexes.put("DiemB", 7);
                diemIndexes.put("DiemC", 8);
                diemIndexes.put("DiemD", 9);
                diemIndexes.put("DiemE", 10);
                int index = diemIndexes.get(mon);
                    for (int i=0;i<listSV.size();i++) {
                        double value =0;
                        {if(index==6){
                            value =listSV.get(i).getDiemA();
                        } else if(index ==7){
                            value =listSV.get(i).getDiemB();}
                            else if(index ==8){
                            value =listSV.get(i).getDiemC();}
                                    else if(index ==9){
                            value =listSV.get(i).getDiemD();}
                                    else if(index ==10){
                            value =listSV.get(i).getDiemE();
                                    }
                        }
                        if ((value >= 0) && (value < 1)) {
                            d0++;
                        } else if ((value >= 1) && (value < 2)) {
                            d1++;
                        } else if ((value >= 2) && (value < 3)) {
                            d2++;
                        } else if ((value >= 3) && (value < 4)) {
                            d3++;
                        } else if ((value >= 4) && (value < 5)) {
                            d4++;
                        } else if ((value >= 5) && (value < 6)) {
                            d5++;
                        } else if ((value >= 6) && (value < 7)) {
                            d6++;
                        } else if ((value >= 7) && (value < 8)) {
                            d7++;d++;
                        } else if ((value >= 8) && (value < 9)) {
                            d8++;
                        } else if ((value >= 9) && (value < 10)) {
                            d9++;
                        } else if ((value == 10)) {
                            d10++;
                        } else {
                            JOptionPane.showMessageDialog(this, "Diem mon hoc khong dung!");
                        }
                    }
                    d=d0+d1+d2+d3+d4+d5+d6+d7+d8+d9+d10;
                    tk00.setText(String.valueOf(String.valueOf(d0)));
                    tk01.setText(String.valueOf(String.valueOf(d1)));
                    tk02.setText(String.valueOf(String.valueOf(d2)));
                    tk03.setText(String.valueOf(String.valueOf(d3)));
                    tk04.setText(String.valueOf(String.valueOf(d4)));
                    tk05.setText(String.valueOf(String.valueOf(d5)));
                    tk06.setText(String.valueOf(String.valueOf(d6)));
                    tk07.setText(String.valueOf(String.valueOf(d7)));
                    tk08.setText(String.valueOf(String.valueOf(d8)));
                    tk09.setText(String.valueOf(String.valueOf(d9)));
                    tk10.setText(String.valueOf(String.valueOf(d10)));
                    tk11.setText(String.valueOf(String.valueOf(d)));
                    Tl0=(double)d0/d*100;
                    Tl1=(double)d1/d*100;
                    Tl2=(double)d2/d*100;
                    Tl3=(double)d3/d*100;
                    Tl4=(double)d4/d*100;
                    Tl5=(double)d5/d*100;
                    Tl6=(double)d6/d*100;
                    Tl7=(double)d7/d*100;
                    Tl8=(double)d8/d*100;
                    Tl9=(double)d9/d*100;
                    x=(double)d10/d*100;
                    Tl=(double)d/d*100;
                    String x0 = String.format("%.2f", Tl0);
                    String x1 = String.format("%.2f", Tl1);
                    String x2 = String.format("%.2f", Tl2);
                    String x3 = String.format("%.2f", Tl3);
                    String x4 = String.format("%.2f", Tl4);
                    String x5 = String.format("%.2f", Tl5);
                    String x6 = String.format("%.2f", Tl6);
                    String x7 = String.format("%.2f", Tl7);
                    String x8 = String.format("%.2f", Tl8);
                    String x9 = String.format("%.2f", Tl9);
                    String x10 = String.format("%.2f", x);
                    String X = String.format("%.2f", Tl);
                    
                    tl00.setText(String.valueOf(x0+"%"));
                    tl01.setText(String.valueOf(x1+"%"));
                    tl02.setText(String.valueOf(x2+"%"));
                    tl03.setText(String.valueOf(x3+"%"));
                    tl04.setText(String.valueOf(x4+"%"));
                    tl05.setText(String.valueOf(x5+"%"));
                    tl06.setText(String.valueOf(x6+"%"));
                    tl07.setText(String.valueOf(x7+"%"));
                    tl08.setText(String.valueOf(x8+"%"));
                    tl09.setText(String.valueOf(x9+"%"));
                    tl10.setText(String.valueOf(x10+"%"));
                    tl11.setText(String.valueOf(X+"%"));    
                    
//                    JOptionPane.showMessageDialog(this, "Ten mon hoc dung!"+ " "+ index + " " + x + " ");
                     return;
                } else {
                    JOptionPane.showMessageDialog(this, "Ten mon hoc khong dung!");
                    return;
                }

            } catch (Exception ex) {
                System.out.println(ex.toString());
            }
    }//GEN-LAST:event_btnTKeActionPerformed
    }

    private void txtMonInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMonInputMethodTextChanged

    }//GEN-LAST:event_txtMonInputMethodTextChanged

    private void tk07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk07ActionPerformed

    private void tk08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk08ActionPerformed

    private void tk09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk09ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk09ActionPerformed

    private void tk10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk10ActionPerformed

    private void tk06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk06ActionPerformed

    private void tl11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tl11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tl11ActionPerformed

    private void tl03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tl03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tl03ActionPerformed

    private void tk11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk11ActionPerformed

    private ArrayList<SinhVien> SVFromFile() throws FileNotFoundException {
        ArrayList<SinhVien> listSV = new ArrayList<SinhVien>();
        try {
            BufferedReader read = new BufferedReader(new FileReader("src/FileData/SinhVien.txt"));
            String line;
            SinhVien SV = null;
            while ((line = read.readLine()) != null) {
                String[] sv = line.split(",");
                String MSV1 = sv[0].trim();
                String Ten1 = sv[1].trim();
                String GioiTinh1 = sv[2].trim();
                String Khoa1 = sv[3].trim();
                String SDT1 = sv[4].trim();
                String Que1 = sv[5].trim();
                double DiemA1 = Double.parseDouble(sv[6].trim());
                double DiemB1 = Double.parseDouble(sv[7].trim());
                double DiemC1 = Double.parseDouble(sv[8].trim());
                double DiemD1 = Double.parseDouble(sv[9].trim());
                double DiemE1 = Double.parseDouble(sv[10].trim());
                SV = new SinhVien(MSV1, Ten1, GioiTinh1, Khoa1, SDT1, Que1, DiemA1, DiemB1, DiemC1, DiemD1, DiemE1);
                listSV.add(SV);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Không tìm thấy tệp tin! ");
            ex.printStackTrace();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        return listSV;
    }

    private ArrayList<MonHoc> MHFromFile() throws FileNotFoundException {
        ArrayList<MonHoc> listMH = new ArrayList<MonHoc>();
        try {
            BufferedReader read = new BufferedReader(new FileReader("src/FileData/Mon.txt"));
            String line;
            MonHoc MH = null;
            while ((line = read.readLine()) != null) {
                String[] mh = line.split(",");
                String Mon1 = mh[0].trim();
                MH = new MonHoc(Mon1);
                listMH.add(MH);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Không tìm thấy tệp tin! ");
            ex.printStackTrace();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        return listMH;
    }

    private boolean checkMon(String Mon1, ArrayList<MonHoc> list) {
        String mon = txtMon.getText();
        for (MonHoc MH : list) {
            if (mon.equals(MH.getMon())) {
                return true;
            }
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tk00;
    private javax.swing.JTextField tk01;
    private javax.swing.JTextField tk02;
    private javax.swing.JTextField tk03;
    private javax.swing.JTextField tk04;
    private javax.swing.JTextField tk05;
    private javax.swing.JTextField tk06;
    private javax.swing.JTextField tk07;
    private javax.swing.JTextField tk08;
    private javax.swing.JTextField tk09;
    private javax.swing.JTextField tk10;
    private javax.swing.JTextField tk11;
    private javax.swing.JTextField tl00;
    private javax.swing.JTextField tl01;
    private javax.swing.JTextField tl02;
    private javax.swing.JTextField tl03;
    private javax.swing.JTextField tl04;
    private javax.swing.JTextField tl05;
    private javax.swing.JTextField tl06;
    private javax.swing.JTextField tl07;
    private javax.swing.JTextField tl08;
    private javax.swing.JTextField tl09;
    private javax.swing.JTextField tl10;
    private javax.swing.JTextField tl11;
    private javax.swing.JTextField txtMon;
    // End of variables declaration//GEN-END:variables
}
