/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.QuanLyKTX;

import javax.swing.JOptionPane;

import Model.PhongKTX;

/**
 *
 * @author Znell
 */
public class DialogSuaPhongKTX extends javax.swing.JDialog {
    private PhongKTX phongKTX;

    /**
     * Creates new form DialogSuaPhongKTX
     */
    public DialogSuaPhongKTX(java.awt.Frame parent, boolean modal, PhongKTX phongKTX) {
        super(parent, modal);
        this.phongKTX = phongKTX;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        tenPhongLabel = new javax.swing.JLabel();
        tenPhongTextfield = new javax.swing.JTextField();
        maPhongLabel = new javax.swing.JLabel();
        maPhongTextfield = new javax.swing.JTextField();
        loaiPhongLabel = new javax.swing.JLabel();
        loaiPhongTextField = new javax.swing.JTextField();
        soSVToiDaLabel = new javax.swing.JLabel();
        soSVToiDaTextField = new javax.swing.JTextField();
        soSVHienTaiLabel = new javax.swing.JLabel();
        soSVHienTaiTextField = new javax.swing.JTextField();
        huyButton = new javax.swing.JButton();
        xacNhanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sửa thông tin phòng " + this.phongKTX.getTenPhong());

        mainLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        mainLabel.setText("Sửa thông tin phòng " + this.phongKTX.getTenPhong());

        tenPhongLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tenPhongLabel.setText("Tên Phòng");

        tenPhongTextfield.setEditable(false);
        tenPhongTextfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tenPhongTextfield.setText(this.phongKTX.getTenPhong());

        maPhongLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        maPhongLabel.setText("Mã Phòng");

        maPhongTextfield.setEditable(false);
        maPhongTextfield.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        maPhongTextfield.setText(this.phongKTX.getMaPhong());

        loaiPhongLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loaiPhongLabel.setText("Loại Phòng");

        loaiPhongTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loaiPhongTextField.setText("" + this.phongKTX.getLoaiPhong());

        soSVToiDaLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        soSVToiDaLabel.setText("Số sinh viên tối đa");

        soSVToiDaTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        soSVToiDaTextField.setText("" + this.phongKTX.getSoSVToiDa());

        soSVHienTaiLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        soSVHienTaiLabel.setText("Số sinh viên hiện tại");

        soSVHienTaiTextField.setEditable(false);
        soSVHienTaiTextField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        soSVHienTaiTextField.setText("" + this.phongKTX.getSoSVHienTai());

        huyButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        huyButton.setText("Hủy bỏ");
        huyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyButtonActionPerformed(evt);
            }
        });

        xacNhanButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        xacNhanButton.setText("Xác nhận");
        xacNhanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacNhanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tenPhongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maPhongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(loaiPhongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(soSVToiDaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(soSVToiDaTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loaiPhongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maPhongTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tenPhongTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(soSVHienTaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(xacNhanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soSVHienTaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(huyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tenPhongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenPhongTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maPhongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maPhongTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loaiPhongLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loaiPhongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soSVToiDaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soSVToiDaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soSVHienTaiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soSVHienTaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xacNhanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>                        

    private void huyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        dispose();
    }                                         

    private void xacNhanButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String loaiPhongMoi = loaiPhongTextField.getText().trim();
        String soSVToiDaMoi = soSVToiDaTextField.getText().trim();

        try {
            Integer.parseInt(loaiPhongMoi);
            Integer.parseInt(soSVToiDaMoi);
        } catch (NumberFormatException  e) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập 1 số nguyên!");
        }

        // trường hợp không thay đổ
        if(Integer.parseInt(loaiPhongMoi) == phongKTX.getLoaiPhong() && Integer.parseInt(soSVToiDaMoi) == phongKTX.getSoSVToiDa()) {
            setVisible(false);
            dispose();
        } else if (Integer.parseInt(soSVToiDaMoi) < phongKTX.getSoSVHienTai()) { // trường hợp số sv tối đa bé hơn số sv hiện tại
            JOptionPane.showMessageDialog(rootPane, "Số sinh viên tối đa có thể ở phải lơn hơn hoặc bằng số sinh viện hiện tại đang ở!");
        } else {
            int respone = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn sửa không?", "Xác nhận sửa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if(respone == JOptionPane.YES_OPTION) {
                this.phongKTX.setLoaiPhong(Integer.parseInt(loaiPhongMoi));
                this.phongKTX.setSoSVToiDa(Integer.parseInt(soSVToiDaMoi));

                if(Integer.parseInt(soSVToiDaMoi) == phongKTX.getSoSVHienTai()) {
                    this.phongKTX.setTinhTrang("hết chỗ");
                }

                dispose();
            }
        }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogSuaPhongKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogSuaPhongKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogSuaPhongKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogSuaPhongKTX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                DialogSuaPhongKTX dialog = new DialogSuaPhongKTX(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton huyButton;
    private javax.swing.JLabel loaiPhongLabel;
    private javax.swing.JTextField loaiPhongTextField;
    private javax.swing.JLabel maPhongLabel;
    private javax.swing.JTextField maPhongTextfield;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel soSVHienTaiLabel;
    private javax.swing.JTextField soSVHienTaiTextField;
    private javax.swing.JLabel soSVToiDaLabel;
    private javax.swing.JTextField soSVToiDaTextField;
    private javax.swing.JLabel tenPhongLabel;
    private javax.swing.JTextField tenPhongTextfield;
    private javax.swing.JButton xacNhanButton;
    // End of variables declaration                   
}
