
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 package GUI.QuanLyKTX;

import GUI.Home;
import java.io.FileNotFoundException;
import java.util.List;

import javax.swing.JFrame;

import Model.PhongKTX;
import Service.PhongKTXService;

/**
 *
 * @author HoangPhuong
 */
public class GUIQuanLyKyTucXa extends javax.swing.JFrame {
    private List<PhongKTX> dsPhong;

    /**
     * Creates new form Demo
     * @throws FileNotFoundException
     */
    public GUIQuanLyKyTucXa() throws FileNotFoundException {
        dsPhong = PhongKTXService.getListPhongFromFile();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        quayLaiButton = new javax.swing.JButton();
        tang2JPanel = new javax.swing.JPanel();
        phongKTXButton202 = new javax.swing.JButton();
        phongKTXButton203 = new javax.swing.JButton();
        phongKTXButton201 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tang1JPanel = new javax.swing.JPanel();
        phongKTXButton101 = new javax.swing.JButton();
        phongKTXButton102 = new javax.swing.JButton();
        phongKTXButton103 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý ký túc xá");
        setSize(new java.awt.Dimension(500, 600));
        setLocationRelativeTo(null);

        quayLaiButton.setText("Quay lại");
        quayLaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quayLaiButtonActionPerformed(evt);
            }
        });

        tang2JPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        phongKTXButton202.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phongKTXButton202.setText("Phòng 202");
        phongKTXButton202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phongKTXButton202ActionPerformed(evt);
            }
        });

        phongKTXButton203.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phongKTXButton203.setText("Phòng 203");
        phongKTXButton203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phongKTXButton203ActionPerformed(evt);
            }
        });

        phongKTXButton201.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phongKTXButton201.setText("Phòng 201");
        phongKTXButton201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phongKTXButton201ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tang2JPanelLayout = new javax.swing.GroupLayout(tang2JPanel);
        tang2JPanel.setLayout(tang2JPanelLayout);
        tang2JPanelLayout.setHorizontalGroup(
            tang2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tang2JPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(phongKTXButton201, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(phongKTXButton202, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(phongKTXButton203, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tang2JPanelLayout.setVerticalGroup(
            tang2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tang2JPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tang2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phongKTXButton201, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phongKTXButton202, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phongKTXButton203, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Tầng 2");

        tang1JPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        phongKTXButton101.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phongKTXButton101.setText("Phòng 101");
        phongKTXButton101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phongKTXButton101ActionPerformed(evt);
            }
        });

        phongKTXButton102.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phongKTXButton102.setText("Phòng 102");
        phongKTXButton102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phongKTXButton102ActionPerformed(evt);
            }
        });

        phongKTXButton103.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        phongKTXButton103.setText("Phòng 103");
        phongKTXButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phongKTXButton103ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tang1JPanelLayout = new javax.swing.GroupLayout(tang1JPanel);
        tang1JPanel.setLayout(tang1JPanelLayout);
        tang1JPanelLayout.setHorizontalGroup(
            tang1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tang1JPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(phongKTXButton101, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(phongKTXButton102, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(phongKTXButton103, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tang1JPanelLayout.setVerticalGroup(
            tang1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tang1JPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(tang1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phongKTXButton101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phongKTXButton102, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phongKTXButton103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Tầng 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(quayLaiButton)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tang2JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tang1JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(quayLaiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(tang2JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tang1JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void quayLaiButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new Home().setVisible(true);
        dispose();
    }                                             

    private void phongKTXButton202ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        PhongKTX phong202 = PhongKTXService.getPhongKTXById(this.dsPhong, "202");
        JFrame newFrame =  new GUIPhongKTX(phong202);
        newFrame.setVisible(true);
        this.setVisible(false);
    }                                                 

    private void phongKTXButton203ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        PhongKTX phong203 = PhongKTXService.getPhongKTXById(this.dsPhong, "203");
        JFrame newFrame =  new GUIPhongKTX(phong203);
        newFrame.setVisible(true);
        this.setVisible(false);
    }                                                 

    private void phongKTXButton201ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        PhongKTX phong201 = PhongKTXService.getPhongKTXById(this.dsPhong, "201");
        JFrame newFrame =  new GUIPhongKTX(phong201);
        newFrame.setVisible(true);
        this.setVisible(false);
    }                                                 

    private void phongKTXButton101ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        PhongKTX phong101 = PhongKTXService.getPhongKTXById(this.dsPhong, "101");
        JFrame newFrame =  new GUIPhongKTX(phong101);
        newFrame.setVisible(true);
        this.setVisible(false);
    }                                                 

    private void phongKTXButton102ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        PhongKTX phong102 = PhongKTXService.getPhongKTXById(this.dsPhong, "102");
        JFrame newFrame =  new GUIPhongKTX(phong102);
        newFrame.setVisible(true);
        this.setVisible(false);
    }                                                 

    private void phongKTXButton103ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        PhongKTX phong103 = PhongKTXService.getPhongKTXById(this.dsPhong, "103");
        JFrame newFrame =  new GUIPhongKTX(phong103);
        newFrame.setVisible(true);
        this.setVisible(false);
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyKyTucXa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyKyTucXa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyKyTucXa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIQuanLyKyTucXa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    JFrame qlktx =  new GUIQuanLyKyTucXa();
                    qlktx.setVisible(true);
                } catch (FileNotFoundException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton phongKTXButton101;
    private javax.swing.JButton phongKTXButton102;
    private javax.swing.JButton phongKTXButton103;
    private javax.swing.JButton phongKTXButton201;
    private javax.swing.JButton phongKTXButton202;
    private javax.swing.JButton phongKTXButton203;
    private javax.swing.JButton quayLaiButton;
    private javax.swing.JPanel tang1JPanel;
    private javax.swing.JPanel tang2JPanel;
    // End of variables declaration                   
}
