/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.ThongKe;

import GUI.Home;
import Model.Khoa;
import Model.SinhVien;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;

/**
 *
 * @author Đặng Huy
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tl08 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tl07 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tk08 = new javax.swing.JTextField();
        tl06 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tk07 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tk06 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tk05 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tk04 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tk03 = new javax.swing.JTextField();
        tk9 = new javax.swing.JTextField();
        tk02 = new javax.swing.JTextField();
        tl9 = new javax.swing.JTextField();
        tk01 = new javax.swing.JTextField();
        tbnTk = new javax.swing.JButton();
        tk00 = new javax.swing.JTextField();
        tl02 = new javax.swing.JTextField();
        tl01 = new javax.swing.JTextField();
        tl00 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tl05 = new javax.swing.JTextField();
        tl04 = new javax.swing.JTextField();
        tl03 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("TRỜ VỀ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(25, 25, 25));
        jLabel16.setText("Khoa");
        jLabel16.setAlignmentY(2.0F);
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("THỐNG KÊ");

        jLabel18.setForeground(new java.awt.Color(25, 25, 25));
        jLabel18.setText("CNTT");
        jLabel18.setAlignmentY(2.0F);
        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl08.setForeground(new java.awt.Color(25, 25, 25));
        tl08.setAlignmentY(2.0F);
        tl08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl08.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel19.setForeground(new java.awt.Color(25, 25, 25));
        jLabel19.setText("Cơ khí");
        jLabel19.setAlignmentY(2.0F);
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl07.setForeground(new java.awt.Color(25, 25, 25));
        tl07.setAlignmentY(2.0F);
        tl07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl07.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel20.setForeground(new java.awt.Color(25, 25, 25));
        jLabel20.setText("Kế toán");
        jLabel20.setAlignmentY(2.0F);
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk08.setForeground(new java.awt.Color(25, 25, 25));
        tk08.setAlignmentY(2.0F);
        tk08.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk08.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl06.setForeground(new java.awt.Color(25, 25, 25));
        tl06.setAlignmentY(2.0F);
        tl06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl06.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel21.setForeground(new java.awt.Color(25, 25, 25));
        jLabel21.setText("Ngôn ngữ Anh");
        jLabel21.setAlignmentY(2.0F);
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel22.setForeground(new java.awt.Color(25, 25, 25));
        jLabel22.setText("Ngôn ngữ Trung");
        jLabel22.setAlignmentY(2.0F);
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel15.setForeground(new java.awt.Color(25, 25, 25));
        jLabel15.setText("Số lượng");
        jLabel15.setAlignmentY(2.0F);
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel23.setForeground(new java.awt.Color(25, 25, 25));
        jLabel23.setText("Ngôn ngữ Nhật");
        jLabel23.setAlignmentY(2.0F);
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk07.setForeground(new java.awt.Color(25, 25, 25));
        tk07.setAlignmentY(2.0F);
        tk07.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk07.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel24.setForeground(new java.awt.Color(25, 25, 25));
        jLabel24.setText("QLKD");
        jLabel24.setAlignmentY(2.0F);
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk06.setForeground(new java.awt.Color(25, 25, 25));
        tk06.setAlignmentY(2.0F);
        tk06.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk06.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel25.setForeground(new java.awt.Color(25, 25, 25));
        jLabel25.setText("QLKS");
        jLabel25.setAlignmentY(2.0F);
        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk05.setForeground(new java.awt.Color(25, 25, 25));
        tk05.setAlignmentY(2.0F);
        tk05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel26.setForeground(new java.awt.Color(25, 25, 25));
        jLabel26.setText("Điện");
        jLabel26.setAlignmentY(2.0F);
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk04.setForeground(new java.awt.Color(25, 25, 25));
        tk04.setAlignmentY(2.0F);
        tk04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(25, 25, 25));
        jLabel27.setText("Tổng");
        jLabel27.setAlignmentY(2.0F);
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk03.setForeground(new java.awt.Color(25, 25, 25));
        tk03.setAlignmentY(2.0F);
        tk03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk9.setForeground(new java.awt.Color(25, 25, 25));
        tk9.setAlignmentY(2.0F);
        tk9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk02.setForeground(new java.awt.Color(25, 25, 25));
        tk02.setAlignmentY(2.0F);
        tk02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl9.setForeground(new java.awt.Color(25, 25, 25));
        tl9.setAlignmentY(2.0F);
        tl9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tk01.setForeground(new java.awt.Color(25, 25, 25));
        tk01.setAlignmentY(2.0F);
        tk01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tbnTk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbnTk.setText("Thống kê");
        tbnTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnTkActionPerformed(evt);
            }
        });

        tk00.setForeground(new java.awt.Color(25, 25, 25));
        tk00.setAlignmentY(2.0F);
        tk00.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tk00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl02.setForeground(new java.awt.Color(25, 25, 25));
        tl02.setAlignmentY(2.0F);
        tl02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl01.setForeground(new java.awt.Color(25, 25, 25));
        tl01.setAlignmentY(2.0F);
        tl01.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl00.setForeground(new java.awt.Color(25, 25, 25));
        tl00.setAlignmentY(2.0F);
        tl00.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel17.setForeground(new java.awt.Color(25, 25, 25));
        jLabel17.setText("Tỷ lệ");
        jLabel17.setAlignmentY(2.0F);
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl05.setForeground(new java.awt.Color(25, 25, 25));
        tl05.setAlignmentY(2.0F);
        tl05.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl04.setForeground(new java.awt.Color(25, 25, 25));
        tl04.setAlignmentY(2.0F);
        tl04.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tl03.setForeground(new java.awt.Color(25, 25, 25));
        tl03.setAlignmentY(2.0F);
        tl03.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tl03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(156, 156, 156))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(138, 138, 138))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(1, 1, 1)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(tk00, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(tk02, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                            .addComponent(tk03, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                            .addComponent(tk04, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                            .addComponent(tk05, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(tk06, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tk08, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tk07, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tk01, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tl01, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tl06, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(tl02, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tl00, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(tl03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tl04, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(tl05, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tl07, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tl08, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(tk9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tl9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(173, 173, 173))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbnTk, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tl00, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tk00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tl01)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tk01, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tk02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tl03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tk03, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tl02, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tk04, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tl04, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tk05, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tl05, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tk06, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tl06, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tk07, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tl07, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tk08)
                    .addComponent(tl08, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tk9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tl9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(tbnTk, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbnTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnTkActionPerformed
        // TODO add your handling code here:
        int d0 = 0;
        double Tl0 = 0;
        int d1 = 0;
        double Tl1 = 0;
        int d2 = 0;
        double Tl2 = 0;
        int d3 = 0;
        double Tl3 = 0;
        int d4 = 0;
        double Tl4 = 0;
        int d5 = 0;
        double Tl5 = 0;
        int d6 = 0;
        double Tl6 = 0;
        int d7 = 0;
        double Tl7 = 0;
        int d8 = 0;
        double Tl8 = 0;
        int d9 = 0;
        double Tl9 = 0;
        String kt = "";
        try {
            ArrayList<Khoa> listNH = NHFromFile();
            ArrayList<SinhVien> listSV = SVFromFile();
            for (int i = 0; i < listSV.size(); i++) {
                d9++;
                kt = listSV.get(i).getKhoa();
                if (kt.equals("CNTT")) {
                    d0++;
                } else if (kt.equals("Cơ khí")) {
                    d1++;
                } else if (kt.equals("Kế toán")) {
                    d2++;
                } else if (kt.equals("Ngôn ngữ Anh")) {
                    d3++;
                } else if (kt.equals("Ngôn ngữ Trung")) {
                    d4++;
                } else if (kt.equals("Ngôn ngữ Nhật")) {
                    d5++;
                } else if (kt.equals("QLKD")) {
                    d6++;
                } else if (kt.equals("QLKS")) {
                    d7++;
                } else if (kt.equals("Điện")) {
                    d8++;
                }
            }
            double value = 0;

            tk00.setText(String.valueOf(String.valueOf(d0)));
            tk01.setText(String.valueOf(String.valueOf(d1)));
            tk02.setText(String.valueOf(String.valueOf(d2)));
            tk03.setText(String.valueOf(String.valueOf(d3)));
            tk04.setText(String.valueOf(String.valueOf(d4)));
            tk05.setText(String.valueOf(String.valueOf(d5)));
            tk06.setText(String.valueOf(String.valueOf(d6)));
            tk07.setText(String.valueOf(String.valueOf(d7)));
            tk08.setText(String.valueOf(String.valueOf(d8)));
            tk9.setText(String.valueOf(String.valueOf(d9)));

            Tl0 = (double) d0 / d9 * 100;
            Tl1 = (double) d1 / d9 * 100;
            Tl2 = (double) d2 / d9 * 100;
            Tl3 = (double) d3 / d9 * 100;
            Tl4 = (double) d4 / d9 * 100;
            Tl5 = (double) d5 / d9 * 100;
            Tl6 = (double) d6 / d9 * 100;
            Tl7 = (double) d7 / d9 * 100;
            Tl8 = (double) d8 / d9 * 100;
            Tl9 = (double) d9 / d9 * 100;
            String x0 = String.format("%.2f", Tl0);
            String x1 = String.format("%.2f", Tl1);
            String x2 = String.format("%.2f", Tl2);
            String x3 = String.format("%.2f", Tl3);
            String x4 = String.format("%.2f", Tl4);
            String x5 = String.format("%.2f", Tl5);
            String x6 = String.format("%.2f", Tl6);
            String x7 = String.format("%.2f", Tl7);
            String x8 = String.format("%.2f", Tl8);
            String x9 = String.format("%.2f", Tl9);
            String X = String.format("%.2f", Tl9);

            tl00.setText(String.valueOf(x0 + "%"));
            tl01.setText(String.valueOf(x1 + "%"));
            tl02.setText(String.valueOf(x2 + "%"));
            tl03.setText(String.valueOf(x3 + "%"));
            tl04.setText(String.valueOf(x4 + "%"));
            tl05.setText(String.valueOf(x5 + "%"));
            tl06.setText(String.valueOf(x6 + "%"));
            tl07.setText(String.valueOf(x7 + "%"));
            tl08.setText(String.valueOf(x8 + "%"));
            tl9.setText(String.valueOf(X + "%"));
            //                    tl11.setText(String.valueOf(index+"%"));
            //        */
            //                JOptionPane.showMessageDialog(this, "Ten mon hoc dung!" + " " + d0 + " " + d1 + " " + d2 + " " + d3 + " " + d4 + " " + d5 + " " + d6 + " " + d7 + " " + d8 + " " + d9);
            return;

        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tbnTkActionPerformed
    private ArrayList<SinhVien> SVFromFile() throws FileNotFoundException {
        ArrayList<SinhVien> listSV = new ArrayList<SinhVien>();
        try {
            BufferedReader read = new BufferedReader(new FileReader("src/FileData/SinhVien.txt"));
            String line;
            SinhVien SV = null;
            while ((line = read.readLine()) != null) {
                String[] sv = line.split(",");
                String MSV1 = sv[0].trim();
                String Ten1 = sv[1].trim();
                String Nganh1 = sv[2].trim();
                String NgaySinh1 = sv[3].trim();
                String GioiTinh1 = sv[4].trim();
                SV = new SinhVien(MSV1, Ten1, Nganh1, NgaySinh1, GioiTinh1);
                listSV.add(SV);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Không tìm thấy tệp tin! ");
            ex.printStackTrace();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        return listSV;
    }

    private ArrayList<Khoa> NHFromFile() throws FileNotFoundException {
        ArrayList<Khoa> listMH = new ArrayList<Khoa>();
        try {
            BufferedReader read = new BufferedReader(new FileReader("src/FileData/Khoa.txt"));
            String line;
            Khoa NH = null;
            while ((line = read.readLine()) != null) {
                String[] mh = line.split(",");
                String NH1 = mh[0].trim();
                NH = new Khoa(NH1);
                listMH.add(NH);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Không tìm thấy tệp tin! ");
            ex.printStackTrace();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        return listMH;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JButton tbnTk;
    private javax.swing.JTextField tk00;
    private javax.swing.JTextField tk01;
    private javax.swing.JTextField tk02;
    private javax.swing.JTextField tk03;
    private javax.swing.JTextField tk04;
    private javax.swing.JTextField tk05;
    private javax.swing.JTextField tk06;
    private javax.swing.JTextField tk07;
    private javax.swing.JTextField tk08;
    private javax.swing.JTextField tk9;
    private javax.swing.JTextField tl00;
    private javax.swing.JTextField tl01;
    private javax.swing.JTextField tl02;
    private javax.swing.JTextField tl03;
    private javax.swing.JTextField tl04;
    private javax.swing.JTextField tl05;
    private javax.swing.JTextField tl06;
    private javax.swing.JTextField tl07;
    private javax.swing.JTextField tl08;
    private javax.swing.JTextField tl9;
    // End of variables declaration//GEN-END:variables
}
